<div class="chatlog__message-group">
  <div id="chatlog__message-container-1120895996516372490" class="chatlog__message-container" data-message-id="1120895996516372490">
    <div class="chatlog__message">
      <div class="chatlog__message-aside">
        <div class="chatlog__reply-symbol"></div><img class="chatlog__avatar" src="https://cdn.discordapp.com/avatars/382314715495399425/3323008de1ce00a014c55874baaebc26.png?size=512" alt="Avatar" loading="lazy">
      </div>
      <div class="chatlog__message-primary">
        <div class="chatlog__reply"><img class="chatlog__reply-avatar" src="https://cdn.discordapp.com/avatars/265102069655011328/69eef639f6394cebf94174d9f174e88c.png?size=512" alt="Avatar" loading="lazy">
          <div class="chatlog__reply-author" style="color:rgb(241,196,15)" title="rinsuki">rinsuki</div>
          <div class="chatlog__reply-content"><span class="chatlog__reply-link" onclick="scrollToMessage(event,'1120859495187353712')"> SwiftのTask、operation が throws なものまで @discardableResult が付いてるのってどこかで議論されていたりしますか？ きちんと処理せずそのまま捨てられることになって微妙なのではと思うのですが…。 <a href="https://developer.apple.com/documentation/swift/task/init(priority:operation:)-5k89c">https://developer.apple.com/documentation/swift/task/init(priority:operation:)-5k89c</a> </span> <span class="chatlog__reply-edited-timestamp" title="06/20/2023 11:35 PM">(edited)</span></div>
        </div>
        <div class="chatlog__header"><span class="chatlog__author" style="color:rgb(233,30,99)" title="shiz1209" data-user-id="382314715495399425">shiz</span> <a href="/channels/291054454793306112?category=main&amp;channel=swift&amp;message_id=1120895996516372490"><span class="chatlog__timestamp"></span></a><a href="#chatlog__message-container-1120895996516372490">06/21/2023 2:00 AM</a></div>
        <div class="chatlog__content chatlog__markdown"><span class="chatlog__markdown-preserve">このThreadとかどうでしょう？ <a href="https://forums.swift.org/t/task-initializer-with-throwing-closure-swallows-error/56066">https://forums.swift.org/t/task-initializer-with-throwing-closure-swallows-error/56066</a></span></div>
        <div class="chatlog__embed">
          <div class="chatlog__embed-color-pill" style="background-color:rgba(17,17,17,255)"></div>
          <div class="chatlog__embed-content-container">
            <div class="chatlog__embed-content">
              <div class="chatlog__embed-text">
                <div class="chatlog__embed-title"><a class="chatlog__embed-title-link" href="https://forums.swift.org/t/task-initializer-with-throwing-closure-swallows-error/56066">
                    <div class="chatlog__markdown chatlog__markdown-preserve">Task initializer with throwing closure swallows error</div>
                  </a></div>
                <div class="chatlog__embed-description">
                  <div class="chatlog__markdown chatlog__markdown-preserve">This is likely well-known at this point, but I wanted to ask about the rationale for this? Specifically, if this was discussed anywhere else on the forums or documented elsewhere, because I couldn't find it when searching. func someFunction() { Task { try await someThrowingFunction() } } This code swallows the error of someThrowingFun...</div>
                </div>
              </div>
              <div class="chatlog__embed-thumbnail-container"><a class="chatlog__embed-thumbnail-link" href="https://images-ext-1.discordapp.net/external/88hU1LfKxeFyWSdlYoQ4j5JtJZsPVThjZ9MCw52kQos/https/global.discourse-cdn.com/swift/original/1X/0a90dde98a223f5841eeca49d89dc9f57592e8d6.png"> <img class="chatlog__embed-thumbnail" src="https://images-ext-1.discordapp.net/external/88hU1LfKxeFyWSdlYoQ4j5JtJZsPVThjZ9MCw52kQos/https/global.discourse-cdn.com/swift/original/1X/0a90dde98a223f5841eeca49d89dc9f57592e8d6.png" alt="Thumbnail" loading="lazy"> </a></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>