<div class="chatlog__message-group">
  <div id="chatlog__message-container-1155225667382812792" class="chatlog__message-container" data-message-id="1155225667382812792">
    <div class="chatlog__message">
      <div class="chatlog__message-aside"><img class="chatlog__avatar" src="https://cdn.discordapp.com/avatars/382314715495399425/3323008de1ce00a014c55874baaebc26.png?size=512" alt="Avatar" loading="lazy"></div>
      <div class="chatlog__message-primary">
        <div class="chatlog__header"><span class="chatlog__author" style="color:rgb(233,30,99)" title="shiz1209" data-user-id="382314715495399425">shiz</span> <a href="/channels/306995750418513920?category=main&amp;channel=swift-2&amp;message_id=1155225667382812792"><span class="chatlog__timestamp" title="Saturday, September 23, 2023 7:34 PM"></span></a><a href="#chatlog__message-container-1155225667382812792">9/23/2023 7:34 PM</a></div>
        <div class="chatlog__content chatlog__markdown"><span class="chatlog__markdown-preserve">ざっと見た感じ↓あたりが変わっているのかなと思いました。 Error typeを()で囲むようにした <code class="chatlog__markdown-pre chatlog__markdown-pre--multiline nohighlight">throws CatError ↓ throws(CatError)</code> rethrowsにも型を指定できるようになった <code class="chatlog__markdown-pre chatlog__markdown-pre--multiline nohighlight">func foo&lt;E: Error&gt;(closure: () throws(E) -&gt; Void) rethrows(E)</code> Resultはtyped errorを返すように変える <code class="chatlog__markdown-pre chatlog__markdown-pre--multiline nohighlight">extension Result { init(catching body: throws(Failure) -&gt; Success) { ... } }</code> 当時よりも型推論がパワーアップしてもっと簡単に書けるようになった。 <code class="chatlog__markdown-pre chatlog__markdown-pre--multiline nohighlight">enum CatError: Error { case sleeps case sitsAtATree } do { try callCat() // throws CatError if something { throw CatError.asleep // throws CatError } } catch .asleep { openFoodCan() } // note: CatError can be thrown out of this do...catch block when the cat isn't asleep**Rationale**: </code></span></div>
      </div>
    </div>
  </div>
</div>