<div class="chatlog__message-group">
  <div id="chatlog__message-container-1188061321648943145" class="chatlog__message-container" data-message-id="1188061321648943145">
    <div class="chatlog__message">
      <div class="chatlog__message-aside"><img class="chatlog__avatar" src="https://cdn.discordapp.com/avatars/189711109966659584/95280765d1be73ce985dce15ea3585f6.png?size=512" alt="Avatar" loading="lazy"></div>
      <div class="chatlog__message-primary">
        <div class="chatlog__header"><span class="chatlog__author" style="color:rgb(237,171,161)" title="omochimetaru" data-user-id="189711109966659584">omochimetaru</span> <a href="/channels/306995750418513920?category=main&amp;channel=swift-2&amp;message_id=1188061510073851964"><span class="chatlog__timestamp" title="Saturday, December 23, 2023 10:11 AM"></span></a><a href="#chatlog__message-container-1188061321648943145">12/23/2023 10:11 AM</a></div>
        <div class="chatlog__content chatlog__markdown"><span class="chatlog__markdown-preserve">
            <div class="chatlog__markdown-quote">
              <div class="chatlog__markdown-quote-border"></div>
              <div class="chatlog__markdown-quote-content">To mitigate this source compatibility problem in Swift 5, throw statements will be treated as always throwing any Error. In Swift 6, they will be treated as throwing the type of their thrown expression. One can enable the Swift 6 behavior with the upcoming feature flag named FullTypedThrows.</div>
            </div>
          </span></div>
      </div>
    </div>
  </div>
  <div id="chatlog__message-container-1188061510073851964" class="chatlog__message-container" data-message-id="1188061510073851964">
    <div class="chatlog__message">
      <div class="chatlog__message-aside">
        <div class="chatlog__short-timestamp" title="Saturday, December 23, 2023 10:12 AM">10:12 AM</div>
      </div>
      <div class="chatlog__message-primary">
        <div class="chatlog__content chatlog__markdown"><span class="chatlog__markdown-preserve">5から使えるけど、throw FooError()の推論が、下位互換を失う挙動に変わるのが、そのフラグ，という事だと思う</span></div>
      </div>
    </div>
  </div>
</div>