<div class="chatlog__message-group">
  <div id="chatlog__message-container-1314427641352163390" class="chatlog__message-container" data-message-id="1314427641352163390">
    <div class="chatlog__message">
      <div class="chatlog__message-aside"><img class="chatlog__avatar" src="https://cdn.discordapp.com/avatars/298037925646565377/2c5f11e0ebd12319d641e006940b1b63.png?size=512" alt="Avatar" loading="lazy"></div>
      <div class="chatlog__message-primary">
        <div class="chatlog__header"><span class="chatlog__author" title="we_channel" data-user-id="298037925646565377">We</span> <a href="/channels/375206337937801216?category=main&amp;channel=swift-zatsu&amp;message_id=1314427641352163390"><span class="chatlog__timestamp" title="Friday, December 6, 2024 3:06 AM"></span></a><a href="#chatlog__message-container-1314427641352163390">12/6/2024 3:06 AM</a></div>
        <div class="chatlog__content chatlog__markdown"><span class="chatlog__markdown-preserve"><code class="chatlog__markdown-pre chatlog__markdown-pre--inline">Task { @MainActor in ...</code>の中だとtyped throwsしてるのにany Errorになっちゃう！なんでか分かります？ <code class="chatlog__markdown-pre chatlog__markdown-pre--multiline language-swift">func f() { Task { @MainActor in do { try throwError() } catch { error // any Errorになる！！ } } } func throwError() throws(FooError) { throw FooError.foo } enum FooError: Error { case foo }</code></span></div>
      </div>
    </div>
  </div>
</div>