<div class="chatlog__message-group">
  <div id="chatlog__message-container-402641258524442635" class="chatlog__message-container" data-message-id="402641258524442635">
    <div class="chatlog__message">
      <div class="chatlog__message-aside"><img class="chatlog__avatar" src="https://cdn.discordapp.com/avatars/387843027072188417/47c96b35135f39a117c2d3e88950c7ab.png?size=512" alt="Avatar" loading="lazy"></div>
      <div class="chatlog__message-primary">
        <div class="chatlog__header"><span class="chatlog__author" style="color:rgb(241,196,15)" title="kuniwak" data-user-id="387843027072188417">Kuniwak</span> <a href="/channels/387857770038427648?category=main&amp;channel=testing&amp;message_id=402641258524442635"><span class="chatlog__timestamp" title="Tuesday, January 16, 2018 1:52 AM"></span></a><a href="#chatlog__message-container-402641258524442635">1/16/2018 1:52 AM</a></div>
        <div class="chatlog__content chatlog__markdown"><span class="chatlog__markdown-preserve">あ、意味がわかりました。異常系のテストでテストを継続できないという話ですね</span></div>
      </div>
    </div>
  </div>
</div>