<div class="chatlog__message-group">
  <div class="chatlog__author-avatar-container">
    <img class="chatlog__author-avatar" src="https://cdn.discordapp.com/avatars/293573633035730946/08ab0592c6064f92c3674e09cc81b5da.png?size=128" alt="Avatar" loading="lazy">
  </div>
  <div class="chatlog__messages">
    <span class="chatlog__author-name" title="hiragram#3838" data-user-id="293573633035730946" style="">hiragram</span>
    <span class="chatlog__timestamp">09-Apr-18 07:17 AM</span>
    <div class="chatlog__message " data-message-id="432801188837195782" id="message-432801188837195782" title="Message sent: 09-Apr-18 07:17 AM">
      <div class="chatlog__content">
        <div class="markdown">
          <span class="preserve-whitespace">テスト対象のコードに直接fatalError書くのやめてthrowしてcatchした所でfatalErrorするようにするくらいしか思い浮かばないけどオーバーキル感ある</span>
        </div>
      </div>
    </div>
    <div class="chatlog__message " data-message-id="432802049974075402" id="message-432802049974075402" title="Message sent: 09-Apr-18 07:20 AM">
      <div class="chatlog__content">
        <div class="markdown">
          <span class="preserve-whitespace">
            <div class="pre pre--multiline language-swift">enum UnrecoverableError: Error { case preconditionFailure } struct Hoge { func テストしたいメソッド() throws { if true { throw UnrecoverableError.preconditionFailure } } } let hoge = Hoge() do { try hoge.テストしたいメソッド() } catch let error as UnrecoverableError { switch error { case .preconditionFailure: preconditionFailure() } }</div> うーんやりたくない
          </span>
        </div>
      </div>
    </div>
  </div>
</div>