<div class="chatlog__message-group">
  <div class="chatlog__author-avatar-container">
    <img class="chatlog__author-avatar" src="https://cdn.discordapp.com/avatars/293624673265123328/accd07acc220a18568ba46a6e9ede18a.png?size=128" alt="Avatar" loading="lazy">
  </div>
  <div class="chatlog__messages">
    <span class="chatlog__author-name" title="koher#9336" data-user-id="293624673265123328" style="color: rgb(17,128,106)">koher</span>
    <span class="chatlog__timestamp">08-Jun-18 02:48 AM</span>
    <div class="chatlog__message " data-message-id="454476755256999946" id="message-454476755256999946" title="Message sent: 08-Jun-18 02:48 AM">
      <div class="chatlog__content">
        <div class="markdown">
          <span class="preserve-whitespace"><span class="mention" title="hironytic#5238">@hironytic</span>
            <div class="quote">あまりわかってませんが、 init(contentsOf:) がthrowsなんなら、 Bundleから読み込む init() のときだけLogic failureなのは辻褄あってない気がしますが。 </div> 一般論として、 <span class="pre pre--inline">foo() throws</span> を用いる関数 <span class="pre pre--inline">bar()</span> が <span class="pre pre--inline">foo() throws</span> がエラーを <span class="pre pre--inline">throw</span> するようなケースを Logic failure とする事前条件を持つことはありえると思います。
          </span>
          <span class="chatlog__edited-timestamp" title="08-Jun-18 02:48 AM">(edited)</span>
        </div>
      </div>
    </div>
  </div>
</div>