<div class="chatlog__message-group">
  <div id="chatlog__message-container-536854668777619457" class="chatlog__message-container" data-message-id="536854668777619457">
    <div class="chatlog__message">
      <div class="chatlog__message-aside"><img class="chatlog__avatar" src="https://cdn.discordapp.com/avatars/189711109966659584/95280765d1be73ce985dce15ea3585f6.png?size=512" alt="Avatar" loading="lazy"></div>
      <div class="chatlog__message-primary">
        <div class="chatlog__header"><span class="chatlog__author" style="color:rgb(237,171,161)" title="omochimetaru" data-user-id="189711109966659584">omochimetaru</span> <a href="/channels/375206337937801216?category=main&amp;channel=swift-zatsu&amp;message_id=536854962190417923"><span class="chatlog__timestamp" title="Monday, January 21, 2019 10:28 AM"></span></a><a href="#chatlog__message-container-536854668777619457">1/21/2019 10:28 AM</a></div>
        <div class="chatlog__content chatlog__markdown"><span class="chatlog__markdown-preserve">ErrorをCustomStringConvertibleにするんじゃなくて、Foundation.LocalizedErrorにして、 <code class="chatlog__markdown-pre chatlog__markdown-pre--inline">var errorDescription: String?</code> を実装してやれば、<code class="chatlog__markdown-pre chatlog__markdown-pre--inline">NSError</code>変換されるときに勝手にlocalizedDescriptionになった。</span></div>
      </div>
    </div>
  </div>
  <div id="chatlog__message-container-536854962190417923" class="chatlog__message-container" data-message-id="536854962190417923">
    <div class="chatlog__message">
      <div class="chatlog__message-aside">
        <div class="chatlog__short-timestamp" title="Monday, January 21, 2019 10:29 AM">10:29 AM</div>
      </div>
      <div class="chatlog__message-primary">
        <div class="chatlog__content chatlog__markdown"><span class="chatlog__markdown-preserve">こうするとXCTestでテストメソッドが例外で失敗したときもちゃんとコンソールに出る。</span></div>
      </div>
    </div>
  </div>
</div>