<div class="chatlog__message-group">
  <div id="chatlog__message-container-583532613940019201" class="chatlog__message-container " data-message-id="583532613940019201">
    <div class="chatlog__message">
      <div class="chatlog__message-aside">
        <img class="chatlog__avatar" src="https://cdn.discordapp.com/avatars/338302215078936576/2f0f5d2880a9a7bdc037652fbade2e9a.png?size=512" alt="Avatar" loading="lazy">
      </div>
      <div class="chatlog__message-primary">
        <div class="chatlog__header">
          <span class="chatlog__author" style="color: rgb(241, 196, 15)" title="hironytic#5238" data-user-id="338302215078936576">hironytic</span>
          <span class="chatlog__timestamp">30-May-19 05:50 AM</span>
        </div>
        <div class="chatlog__content chatlog__markdown">
          <span class="chatlog__markdown-preserve">ただ、build-scriptに <span class="chatlog__markdown-pre chatlog__markdown-pre--inline">--foundation --xctest --test</span> を渡して実行しても、本体側の？テストケースは実行されるっぽいけど、Foundation側のテストは実行されてないっぽいんですよね。</span>
        </div>
      </div>
    </div>
  </div>
  <div id="chatlog__message-container-583532825068699658" class="chatlog__message-container " data-message-id="583532825068699658">
    <div class="chatlog__message">
      <div class="chatlog__message-aside">
        <div class="chatlog__short-timestamp" title="30-May-19 05:51 AM">05:51</div>
      </div>
      <div class="chatlog__message-primary">
        <div class="chatlog__content chatlog__markdown">
          <span class="chatlog__markdown-preserve">というのも、 Foundation側のテストを一部書き換えて必ずコケるようにしたけど、そこはログに上がらなかったし、Failureの数も変わらなかったので。</span>
        </div>
      </div>
    </div>
  </div>
</div>