<div class="chatlog__message-group">
  <div id="chatlog__message-container-635729934479917056" class="chatlog__message-container " data-message-id="635729934479917056">
    <div class="chatlog__message">
      <div class="chatlog__message-aside">
        <img class="chatlog__avatar" src="https://cdn.discordapp.com/avatars/293624673265123328/accd07acc220a18568ba46a6e9ede18a.png?size=512" alt="Avatar" loading="lazy">
      </div>
      <div class="chatlog__message-primary">
        <div class="chatlog__header">
          <span class="chatlog__author" style="color: rgb(17, 128, 106)" title="koher#9336" data-user-id="293624673265123328">koher</span>
          <a href="/channels/306995750418513920?category=main&amp;channel=swift-2&amp;message_id=635732025541918740"><span class="chatlog__timestamp">21-Oct-19 06:43 AM</span></a>
        </div>
        <div class="chatlog__content chatlog__markdown">
          <span class="chatlog__markdown-preserve">Javaではその二つが両方Throwableで表してるけど。というか、検査例外と非検査例外が同じthrows/throwで表されてるのが良くないのかな。</span>
        </div>
      </div>
    </div>
  </div>
  <div id="chatlog__message-container-635730285371195392" class="chatlog__message-container " data-message-id="635730285371195392">
    <div class="chatlog__message">
      <div class="chatlog__message-aside">
        <div class="chatlog__short-timestamp" title="21-Oct-19 06:45 AM">06:45</div>
      </div>
      <div class="chatlog__message-primary">
        <div class="chatlog__content chatlog__markdown">
          <span class="chatlog__markdown-preserve">throws Error とthrows Never 的サブタイピングを考えるとThrowableでまとめるのに無理がありそうって意味。</span>
        </div>
      </div>
    </div>
  </div>
  <div id="chatlog__message-container-635730589445783562" class="chatlog__message-container " data-message-id="635730589445783562">
    <div class="chatlog__message">
      <div class="chatlog__message-aside">
        <div class="chatlog__short-timestamp" title="21-Oct-19 06:46 AM">06:46</div>
      </div>
      <div class="chatlog__message-primary">
        <div class="chatlog__content chatlog__markdown">
          <span class="chatlog__markdown-preserve">そうすると検査例外が親じゃないといけないけど、そしたら↑の非検査例外巻き込みが起こるから、別系統にして構文も変えるのが良さそう。</span>
        </div>
      </div>
    </div>
  </div>
  <div id="chatlog__message-container-635731250052595722" class="chatlog__message-container " data-message-id="635731250052595722">
    <div class="chatlog__message">
      <div class="chatlog__message-aside">
        <div class="chatlog__short-timestamp" title="21-Oct-19 06:49 AM">06:49</div>
      </div>
      <div class="chatlog__message-primary">
        <div class="chatlog__content chatlog__markdown">
          <span class="chatlog__markdown-preserve">Swiftが非検査例外（Logic Failure）の構文をthrows/tryから分離したのは正しそうだなぁ。あとは、↓とかで非検査例外のハンドリングがサポートされれば…。 <a href="https://gist.github.com/lattner/31ed37682ef1576b16bca1432ea9f782#part-3-reliability-through-fault-isolation">https://gist.github.com/lattner/31ed37682ef1576b16bca1432ea9f782#part-3-reliability-through-fault-isolation</a></span>
        </div>
        <div class="chatlog__embed">
          <div class="chatlog__embed-color-pill" style="background-color: rgba(30, 35, 39, 255)"></div>
          <div class="chatlog__embed-content-container">
            <div class="chatlog__embed-content">
              <div class="chatlog__embed-text">
                <div class="chatlog__embed-title">
                  <a class="chatlog__embed-title-link" href="https://gist.github.com/lattner/31ed37682ef1576b16bca1432ea9f782">
                    <div class="chatlog__markdown chatlog__markdown-preserve">Swift Concurrency Manifesto</div>
                  </a>
                </div>
                <div class="chatlog__embed-description">
                  <div class="chatlog__markdown chatlog__markdown-preserve">Swift Concurrency Manifesto. GitHub Gist: instantly share code, notes, and snippets.</div>
                </div>
              </div>
              <div class="chatlog__embed-thumbnail-container">
                <a class="chatlog__embed-thumbnail-link" href="https://images-ext-1.discordapp.net/external/v2ToTBFZ7zHPk2sQlBt80EaH2hhwBfD3Zdf1J_uxMxs/https/github.githubassets.com/images/modules/gists/gist-og-image.png">
                  <img class="chatlog__embed-thumbnail" src="https://images-ext-1.discordapp.net/external/v2ToTBFZ7zHPk2sQlBt80EaH2hhwBfD3Zdf1J_uxMxs/https/github.githubassets.com/images/modules/gists/gist-og-image.png" alt="Thumbnail" loading="lazy">
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div id="chatlog__message-container-635732025541918740" class="chatlog__message-container " data-message-id="635732025541918740">
    <div class="chatlog__message">
      <div class="chatlog__message-aside">
        <div class="chatlog__short-timestamp" title="21-Oct-19 06:52 AM">06:52</div>
      </div>
      <div class="chatlog__message-primary">
        <div class="chatlog__content chatlog__markdown">
          <span class="chatlog__markdown-preserve"><span class="chatlog__markdown-mention" title="kishikawakatsumi#7600">@Kishikawa Katsumi</span> JavaのAPIの例外の使い方が良くないというのは僕もそうじゃないかと思ってましたが、　<span class="chatlog__markdown-pre chatlog__markdown-pre--inline">parseInt</span> の　<span class="chatlog__markdown-pre chatlog__markdown-pre--inline">NumberFormatException</span> が非検査例外なのが飛び抜けてヤバいのに印象が引っぱられてて、他はそうでもないと思うようになりました。</span>
        </div>
      </div>
    </div>
  </div>
</div>