<div class="chatlog__message-group">
  <div id="chatlog__message-container-870577899546238996" class="chatlog__message-container" data-message-id="870577899546238996">
    <div class="chatlog__message">
      <div class="chatlog__message-aside"><img class="chatlog__avatar" src="https://cdn.discordapp.com/embed/avatars/2.png" alt="Avatar" loading="lazy"></div>
      <div class="chatlog__message-primary">
        <div class="chatlog__header"><span class="chatlog__author" title="nanasi_" data-user-id="504646030403436544">nanasi</span> <a href="/channels/291054454793306112?category=main&amp;channel=swift&amp;message_id=870577899546238996"><span class="chatlog__timestamp" title="Friday, July 30, 2021 8:05 AM"></span></a><a href="#chatlog__message-container-870577899546238996">7/30/2021 8:05 AM</a></div>
        <div class="chatlog__content chatlog__markdown"><span class="chatlog__markdown-preserve">Failureを明示的に持たせる意味がよくわからなくて…、将来<code class="chatlog__markdown-pre chatlog__markdown-pre--inline">typed throws</code>に対応したときのためのシグネチャ的な感じなんですかね<img loading="lazy" class="chatlog__emoji " alt="🤔" title="thinking" src="https://cdn.jsdelivr.net/gh/twitter/twemoji@latest/assets/svg/1f914.svg"></span></div>
      </div>
    </div>
  </div>
</div>