<div class="chatlog__message-group">
  <div class="chatlog__reference-symbol"></div>
  <div class="chatlog__reference">
    <img class="chatlog__reference-avatar" src="https://cdn.discordapp.com/avatars/291062140079570944/75d22639a88c37be90cb60118acb7df5.png?size=128" alt="Avatar" loading="lazy">
    <span class="chatlog__reference-name" title="kateinoigakukun#2184" style="color: rgb(241,196,15)">kateinoigakukun</span>
    <div class="chatlog__reference-content">
      <span class="chatlog__reference-link" onclick="scrollToMessage(event, '881494144281886751')"> キャンセルされたかどうかはthrowされたエラーで決められるのではなく、 <span class="pre pre--inline">cancel</span> メソッドを呼んだレシーバのTaskに対してキャンセルフラグが立つ実装になっています。 </span>
    </div>
  </div>
  <div class="chatlog__author-avatar-container">
    <img class="chatlog__author-avatar" src="https://cdn.discordapp.com/avatars/293624673265123328/accd07acc220a18568ba46a6e9ede18a.png?size=128" alt="Avatar" loading="lazy">
  </div>
  <div class="chatlog__messages">
    <span class="chatlog__author-name" title="koher#9336" data-user-id="293624673265123328" style="color: rgb(17,128,106)">koher</span>
    <span class="chatlog__timestamp">29-Aug-21 11:04 AM</span>
    <div class="chatlog__message " data-message-id="881494625515356190" id="message-881494625515356190" title="Message sent: 29-Aug-21 11:04 AM">
      <div class="chatlog__content">
        <div class="markdown">
          <span class="preserve-whitespace">
            <div class="quote"> cancel メソッドを呼んだレシーバのTaskに対してキャンセルフラグが立つ実装 </div>それを受けて、非同期 API 実装側は <span class="pre pre--inline">Task.checkCancellation()</span> を呼ぶか、 <span class="pre pre--inline">Task.isCancelled</span> をチェックして適切な処理を行った後に <span class="pre pre--inline">CancellationError</span> を <span class="pre pre--inline">throw</span> するというルールなのかと思っていました。
          </span>
        </div>
      </div>
    </div>
  </div>
</div>